# -*- coding: utf-8 -*-
"""Aula_14_Scipy_teste_t

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CZxiet1O7jasd3ry_4gEEqTwXYWxQmPj
"""

# -*- coding: utf-8 -*-

# Importa as bibliotecas necessárias
import numpy as np
from scipy import stats

# --- 1. Simulação dos Dados do Experimento ---
# Delineamento Inteiramente Casualizado (DIC)
# Medida: Teor de canabinoides (%)
# Tratamentos: 3 temperaturas de secagem

# Parâmetros da simulação
np.random.seed(42) # Define uma semente para que os resultados aleatórios sejam sempre os mesmos
num_amostras_por_tratamento = 10 # Número de repetições (plantas) por tratamento

# Simulando os dados para cada tratamento
# Vamos supor que 50°C é uma temperatura ótima, 45°C é boa e 55°C já degrada um pouco.
# loc = média do teor de canabinoides; scale = desvio padrão
tratamento_45C = np.random.normal(loc=18.5, scale=1.5, size=num_amostras_por_tratamento)
tratamento_50C = np.random.normal(loc=20.5, scale=1.2, size=num_amostras_por_tratamento)
tratamento_55C = np.random.normal(loc=17.0, scale=1.8, size=num_amostras_por_tratamento)

# Imprime os dados simulados para conferência
print("--- Dados Simulados do Teor de Canabinoides (%) ---")
print(f"Tratamento 45°C: {np.round(tratamento_45C, 2)}")
print(f"Tratamento 50°C: {np.round(tratamento_50C, 2)}")
print(f"Tratamento 55°C: {np.round(tratamento_55C, 2)}")
print("-" * 50)


# --- 2. Análise Estatística ---

# Passo A: Análise de Variância (ANOVA)
# A ANOVA é o teste correto para comparar 3 ou mais grupos.
# Hipótese Nula (H0): As médias de todos os tratamentos são iguais.
# Hipótese Alternativa (H1): Pelo menos uma média é diferente.
print("\n--- Passo A: Análise de Variância (ANOVA) ---")
f_statistic, p_value_anova = stats.f_oneway(tratamento_45C, tratamento_50C, tratamento_55C)

print(f"Estatística F: {f_statistic:.4f}")
print(f"P-valor da ANOVA: {p_value_anova:.4f}")

# Interpretação da ANOVA
alpha = 0.05
if p_value_anova < alpha:
    print("\nResultado ANOVA: Rejeitamos a hipótese nula (p < 0.05).")
    print("Conclusão: Existe uma diferença estatisticamente significativa entre as médias dos tratamentos de secagem.")
    prosseguir_com_t_test = True
else:
    print("\nResultado ANOVA: Não rejeitamos a hipótese nula (p >= 0.05).")
    print("Conclusão: Não há evidência de diferença significativa entre as médias dos tratamentos.")
    prosseguir_com_t_test = False
print("-" * 50)


# Passo B: Testes t par-a-par (Post-Hoc)
# Este passo só é executado se a ANOVA for significativa.
if prosseguir_com_t_test:
    print("\n--- Passo B: Testes t para Comparações Múltiplas ---")
    print("Comparando os pares de tratamentos para ver onde estão as diferenças.\n")

    # Comparações
    comparacoes = [
        ("45°C", "50°C", tratamento_45C, tratamento_50C),
        ("45°C", "55°C", tratamento_45C, tratamento_55C),
        ("50°C", "55°C", tratamento_50C, tratamento_55C)
    ]

    for nome1, nome2, dados1, dados2 in comparacoes:
        # Teste t para amostras independentes
        t_stat, p_value_t = stats.ttest_ind(dados1, dados2)

        print(f"Comparação: {nome1} vs {nome2}")
        print(f"  - Estatística t: {t_stat:.4f}")
        print(f"  - P-valor do Teste t: {p_value_t:.4f}")

        # Interpretação do teste t
        if p_value_t < alpha:
            print(f"  - Conclusão: Diferença SIGNIFICATIVA encontrada entre {nome1} e {nome2}.")
        else:
            print(f"  - Conclusão: Diferença NÃO significativa entre {nome1} e {nome2}.")
        print()
else:
    print("\nComo a ANOVA não foi significativa, não se prossegue com os testes t par-a-par.")